from building import *
Import('RTT_ROOT')
Import('rtconfig')

cwd = GetCurrentDir()
src = Glob('*.c')+Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('In_Out_Devs', src, depend=[''], CPPPATH=CPPPATH)

Return('group')
